language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=tests/
after_success:
  - coveralls
