site_name: FastAPI JWT Auth
site_description: FastAPI extension that provides JWT Auth support (secure, easy to use, and lightweight)
theme:
  name: material

repo_name: IndominusByte/fastapi-jwt-auth
repo_url: https://github.com/IndominusByte/fastapi-jwt-auth

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - About: index.md
  - Installation: installation.md
  - Usage:
    - Basic Usage: usage/basic.md
    - Partially Protecting: usage/optional.md
    - Refresh Tokens: usage/refresh.md
    - Token Freshness: usage/freshness.md
    - Token Revoking: usage/revoking.md
  - Configuration Options:
    - General Options: configuration-options/general.md
    - Headers Options: configuration-options/headers.md
    - Cookies Options: configuration-options/cookies.md
    - CSRF Options: configuration-options/csrf.md
    - Denylist Options: configuration-options/denylist.md
