site_name: FastAPI JWT Auth
site_description: FastAPI extension that provides JWT Auth support (secure, easy to use, and lightweight)
theme:
  name: material
  palette:
    primary: black

repo_name: IndominusByte/fastapi-jwt-auth
repo_url: https://github.com/IndominusByte/fastapi-jwt-auth

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - attr_list
  - def_list
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - About: index.md
  - Usage:
    - Basic Usage: usage/basic.md
    - Partially Protecting: usage/optional.md
    - Refresh Tokens: usage/refresh.md
    - Freshness Tokens: usage/freshness.md
    - Revoking Tokens: usage/revoking.md
    - JWT in Cookies: usage/jwt_in_cookies.md
  - Configuration Options:
    - General Options: configuration/general.md
    - Headers Options: configuration/headers.md
    - Denylist Options: configuration/denylist.md
    - Cookies Options: configuration/cookies.md
    - CSRF Options: configuration/csrf.md
